Milestone six
mesielepush/ror-social-scaffold pull request #4
Opened 2020-02-13 01:14 UTC by mesielepush

2020-02-13 01:15 UTC, mesielepush commented
Two columns for friendship, to upgrade friends search.

2020-02-13 06:36 UTC, maelfosso requested changes
# Change required :red_circle: 

Hello @mesielepush 

THe project is almost OK. 
There is that error after accepting the friendship request.
![Screenshot from 2020-02-13 01-28-14](https://user-images.githubusercontent.com/8848104/74407642-6504c780-4e00-11ea-96e0-e2f3e2f721b3.png)

Kindly, fix that and submit a new code review request.
Thanks

Mael FOSSO

2020-02-13 19:37 UTC, samgaco commented
Hi @mesielepush :high_brightness: 

I have tried to verify the previous requirement, but I seem not to be able to send a friend requests:


![request](https://user-images.githubusercontent.com/34820784/74471307-49e99480-4ea0-11ea-83ba-32777ea0372b.png)

Please submit back once that is fixed. Every user on the list should[ show an option at the side to send friend requests](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png), and a user should not be able to see itself in such list.

--------------------

* ###### STATUS OF THE MILESTONE: REQUESTED CHANGES :stop_sign:

2020-02-13 20:10 UTC, mesielepush commented
That is not the UI of mine, I don't know where that caption of yours came from. The friendship request is on the profile of every user. But I'll will put it on the friends index as well.

2020-02-14 02:43 UTC, maelfosso approved these changes
# Congratulations :clap: 

Well done job :+1: 
You can merge it :smile: 

Good luck with the next milestone

Mael FOSSO

2020-02-14 02:43 UTC, maelfosso commented on app/views/users/show.html.erb
> +    <h3> Lastest %> </h3>
Correct that text

2020-02-14 02:43 UTC, maelfosso commented on app/views/users/show.html.erb
> +          <%= link_to 'request_friendship', request_friendship_path(user_id: current_user.id, friend_id: @user.id), class:'btn btn-info' %>
Don't you want to write `request friendship` here?

2020-02-14 13:57 UTC, merged